# Generated by Django 3.2.5 on 2021-07-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='pessoa',
            new_name='usuario',
        ),
    ]
