# Generated by Django 3.2.5 on 2021-07-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_rename_pessoa_receita_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='usuario',
            new_name='pessoa',
        ),
    ]
